services:
  jupyterhub:
    build: .
    ports:
      - '80:8000'
    volumes:
      #- save_admin:/home/admin
      - save_home:/home
      - ${NOTEBOOKS_FROM}:${HUB_PATH}
  # NOTEBOOKS_FROM HUB_PATH - переменные (Я использую из variables.env)
volumes:
  save_home:
  #save_admin: